{{- $_ := required "Namespace is required" .Release.Namespace }}
{{- $_ := required "Name of operator is required." $.Values.name }}
{{- $_ := required "Docker Repository FQDN path is required" .Values.global.provider.registry.fqdn }}
{{- $jsonKey := include "confluent-operator.imagePullSecret" . | quote }}
{{- if .Capabilities.APIVersions.Has "v1" }}
apiVersion: apps/v1
{{ else if .Capabilities.APIVersions.Has "v1beta2" }}
apiVersion: apps/v1beta2
{{- else }}
apiVersion: apps/v1beta1
{{- end }}
kind: Deployment
metadata:
  {{- include "confluent-operator.labels" . }}
  name: {{ .Values.name }}
  namespace:  {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "7778"
        prometheus.io/scrape: "true"
      labels:
        app: {{ .Values.name }}
    spec:
      {{- if not (empty $.Values.affinity) }}
      affinity:
{{ toYaml .Values.affinity | trim | indent 8 }}
      {{- end }}
      {{- if not (empty $.Values.tolerations) }}
      tolerations:
{{ toYaml .Values.tolerations | trim | indent 6 }}
      {{- end }}
      containers:
      - args:
        - controller
        - --proxy={{ .Values.global.provider.name }}
        {{- if contains "aws" .Values.global.provider.name }}
        - --region={{ .Values.global.provider.region }}
        {{- end }}
        {{- if .Values.debug }}
        - --debug
        {{- end }}
        - --disable-pod-controller
        - --provider=on-prem
        - --prefixed-secrets
        - --disable-hostpath
        - --enable-logical-cluster-secrets=false
        - --enable-kafka-roll-controller=true
        {{- if .Values.metrics.dataDog.enabled }}
        - --enable-data-dog-exporter
        - --datadog-agent-port={{ .Values.metrics.dataDog.port }}
        {{- end }}
        {{- if .Values.metrics.prometheus.enabled }}
        - --enable-prometheus-exporter
        - --prometheus-port={{ .Values.metrics.prometheus.port }}
        {{- end }}
        {{- if .Values.namespaced }}
        - --namespace={{ .Release.Namespace }}
        {{- end }}
        {{- if or (.Values.namespaced) (not .Values.installClusterResources) }}
        - --installCRDs=false
        {{- end }}
        name: {{ .Values.name }}
        image: {{ .Values.global.provider.registry.fqdn }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        {{- if .Values.debug }}
        env:
        - name: ENABLE_DEBUG
          value: "true"
        {{- end }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      serviceAccountName: {{ .Values.name }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
