apiVersion: v1
description: A Helm chart for Kubernetes to deploy Confluent Platform.
name: confluent-operator
version: 1.6.0
appVersion: "1.0"
keywords:
- Confluent Operator
- Kafka
- Zookeeper
- Connect
- Replicator
- SchemaRegistry
- KSQL
- ControlCenter
home: https://www.confluent.io/
engine: gotpl
namespace: confluent-operator
sources:
  - https://docs.confluent.io/current/installation/operator/index.html
maintainers:
  - name: Confluent Cloud
    email: operator@confluent.io
tillerVersion: ">=2.9"

