apiVersion: v1
description: A Helm chart for Kubernetes to deploy Replicator cluster
name: replicator
version: 1.6.0
appVersion: "1.0"
keywords:
- Replicator
- Connector
- Confluent Component
home: https://www.confluent.io/
engine: gotpl
namespace: confluent-operator
sources:
  - https://docs.confluent.io/current/index.html
maintainers:
  - name: Confluent Cloud
    email: operator@confluent.io
tillerVersion: ">=2.9"