apiVersion: v1
kind: Secret
metadata:
  {{- include "confluent-operator.labels" . }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-sslcerts
type: Opaque
{{- if .Values.tls.jmxTLS }}
{{- $_ := required "Fullchain PEM cannot be empty" $.Values.tls.fullchain }}
{{- $_ := required "Private key pem cannot be empty." $.Values.tls.privkey }}
data:
  fullchain.pem: {{ .Values.tls.fullchain | b64enc }}
  privkey.pem: {{ .Values.tls.privkey | b64enc }}
  {{- if .Values.tls.cacerts }}
  cacerts.pem: {{ .Values.tls.cacerts | b64enc }}
  {{- end }}
{{- end }}
